version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:1000" # Port exposé pour ton backend
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/bootapp

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Port exposé pour ton frontend
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
